var to_be_iru = [
  new Term('いる', null, null, 'to be (animate)'),
];

var to_be_aru = [
  new Term('ある', null, null, 'to be (inanimate)'),
];

var irregular_suru = [
  new Term('する', '為る', '<ruby>為<rp>(</rp><rt>な</rt><rp>)</rp></ruby>る', 'to do'),
];

var irregular_kuru = [
  new Term('くる', '来る', '<ruby>来<rp>(</rp><rt>く</rt><rp>)</rp></ruby>る', 'to come'),
]

var ichidan = [
  new Term('あける', '開ける', '<ruby>開<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>ける', 'to open'),
  new Term('あげる', null, null, 'to give'),
  new Term('あつめる', '集める', '<ruby>集<rp>(</rp><rt>あつ</rt><rp>)</rp></ruby>める', 'to gather, collect'),
  new Term('あびる', '浴びる', '<ruby>浴<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>びる', 'to bathe, take a shower'),
  new Term('あわてる', '慌てる', '<ruby>慌<rp>(</rp><rt>あわ</rt><rp>)</rp></ruby>てる', 'to panic, be flustered'),
  new Term('いいつける', '言いつける', '<ruby>言<rp>(</rp><rt>い</rt><rp>)</rp></ruby>いつける', 'to command'),
  new Term('いきる', '生きる', '<ruby>生<rp>(</rp><rt>い</rt><rp>)</rp></ruby>きる', 'to be alive'),
  new Term('いじめる', '虐める', '<ruby>虐<rp>(</rp><rt>いじ</rt><rp>)</rp></ruby>める', 'to torment, bully'),
  new Term('いましめる', '戒める', '<ruby>戒<rp>(</rp><rt>いまし</rt><rp>)</rp></ruby>める', 'to tell off, caution'),
  new Term('いる', '居る', '<ruby>居<rp>(</rp><rt>お</rt><rp>)</rp></ruby>る', 'to be'),
  new Term('いれる', '入れる', '<ruby>入<rp>(</rp><rt>い</rt><rp>)</rp></ruby>れる', 'to put in, let in'),
  new Term('うまれる', '生まれる', '<ruby>生<rp>(</rp><rt>う</rt><rp>)</rp></ruby>まれる', 'to be born'),
  new Term('える', '得る', '<ruby>得<rp>(</rp><rt>え</rt><rp>)</rp></ruby>る', 'to get'),
  new Term('おきる', '起きる', '<ruby>起<rp>(</rp><rt>お</rt><rp>)</rp></ruby>きる', 'to wake up; to occur'),
  new Term('おくれる', '遅れる', '<ruby>遅<rp>(</rp><rt>おく</rt><rp>)</rp></ruby>れる', 'to be late, lag behind'),
  new Term('おさえる', '抑える', '<ruby>抑<rp>(</rp><rt>おさ</rt><rp>)</rp></ruby>える', 'to restrain, control'),
  new Term('おしえる', '教える', '<ruby>教<rp>(</rp><rt>おし</rt><rp>)</rp></ruby>える', 'to teach, show'),
  new Term('おそれる', '恐れる', '<ruby>恐<rp>(</rp><rt>おそ</rt><rp>)</rp></ruby>れる', 'to fear, be in awe of'),
  new Term('おちる', '落ちる', '<ruby>落<rp>(</rp><rt>お</rt><rp>)</rp></ruby>ちる', 'to fall, fail, go down'),
  new Term('おぼえる', '覚える', '<ruby>覚<rp>(</rp><rt>おぼ</rt><rp>)</rp></ruby>える', 'to remember, learn'),
  new Term('おりる', '降りる', '<ruby>降<rp>(</rp><rt>お</rt><rp>)</rp></ruby>りる', 'to get off, go down'),
  new Term('おれる', '折れる', '<ruby>折<rp>(</rp><rt>お</rt><rp>)</rp></ruby>れる', 'to be broken, snap'),
  new Term('かえる', '変える', '<ruby>変<rp>(</rp><rt>か</rt><rp>)</rp></ruby>える', 'to change'),
  new Term('かえる', '換える', '<ruby>換<rp>(</rp><rt>か</rt><rp>)</rp></ruby>える', 'to get changed'),
  new Term('かかえる', '抱える', '<ruby>抱<rp>(</rp><rt>かか</rt><rp>)</rp></ruby>える', 'to hold (in your arms), have'),
  new Term('かかげる', '掲げる', '<ruby>掲<rp>(</rp><rt>かか</rt><rp>)</rp></ruby>げる', 'to raise (a flag), hold up'),
  new Term('かける', null, null, 'to hang, sit, telephone, risk'),
  new Term('かさねる', '重ねる', '<ruby>重<rp>(</rp><rt>かさ</rt><rp>)</rp></ruby>ねる', 'to pile up, repeat'),
  new Term('かじる', '齧る', '<ruby>齧<rp>(</rp><rt>かじ</rt><rp>)</rp></ruby>る', 'to gnaw, nibble'),
  new Term('かぞえる', '数える', '<ruby>数<rp>(</rp><rt>かぞ</rt><rp>)</rp></ruby>える', 'to count'),
  new Term('かたづける', '片付ける', '<ruby>片<rp>(</rp><rt>かた</rt><rp>)</rp></ruby><ruby>付<rp>(</rp><rt>づ</rt><rp>)</rp></ruby>ける', 'to finish, tidy up'),
  new Term('かためる', '固める', '<ruby>固<rp>(</rp><rt>かた</rt><rp>)</rp></ruby>める', 'to strengthen, harden'),
  new Term('かまえる', '構える', '<ruby>構<rp>(</rp><rt>かま</rt><rp>)</rp></ruby>える', 'to stand prepared'),
  new Term('かりる', '借りる', '<ruby>借<rp>(</rp><rt>か</rt><rp>)</rp></ruby>りる', 'to borrow, rent'),
  new Term('かれる', '枯れる', '<ruby>枯<rp>(</rp><rt>か</rt><rp>)</rp></ruby>れる', 'to wither'),
  new Term('かんがえる', '考える', '<ruby>考<rp>(</rp><rt>かんが</rt><rp>)</rp></ruby>える', 'to think'),
  new Term('かんじる', '感じる', '<ruby>感<rp>(</rp><rt>かん</rt><rp>)</rp></ruby>じる', 'to feel, sense'),
  new Term('きえる', '消える', '<ruby>消<rp>(</rp><rt>き</rt><rp>)</rp></ruby>える', 'to vanish, go out, be extinguished'),
  new Term('きこえる', '聞こえる', '<ruby>聞<rp>(</rp><rt>き</rt><rp>)</rp></ruby>こえる', 'to be audible, able to hear'),
  new Term('きずつける', '傷つける', '<ruby>傷<rp>(</rp><rt>きず</rt><rp>)</rp></ruby>つける', 'to wound, damage, harm'),
  new Term('きめる', '決める', '<ruby>決<rp>(</rp><rt>き</rt><rp>)</rp></ruby>める', 'to decide, choose'),
  new Term('きる', '着る', '<ruby>着<rp>(</rp><rt>き</rt><rp>)</rp></ruby>る', 'to wear'),
  new Term('きれる', '切れる', '<ruby>切<rp>(</rp><rt>き</rt><rp>)</rp></ruby>れる', 'to break, cut off, expire'),
  new Term('きんじる', '禁じる', '<ruby>禁<rp>(</rp><rt>きん</rt><rp>)</rp></ruby>じる', 'to ban, prohibit'),
  new Term('くずれる', '崩れる', '<ruby>崩<rp>(</rp><rt>くず</rt><rp>)</rp></ruby>れる', 'to collapse, cave in'),
  new Term('くらべる', '比べる', '<ruby>比<rp>(</rp><rt>くら</rt><rp>)</rp></ruby>べる', 'to compare'),
  new Term('くるしめる', '苦しめる', '<ruby>苦<rp>(</rp><rt>くる</rt><rp>)</rp></ruby>しめる', 'to inflict pain, torment'),
  new Term('くれる', '呉れる', '<ruby>呉<rp>(</rp><rt>く</rt><rp>)</rp></ruby>れる', 'to give (the giver is not the speaker)'),
  new Term('くれる', '暮れる', '<ruby>暮<rp>(</rp><rt>く</rt><rp>)</rp></ruby>れる', 'to grow dark (sunset)'),
  new Term('くわえる', '加える', '<ruby>加<rp>(</rp><rt>くわ</rt><rp>)</rp></ruby>える', 'to add to, include'),
  new Term('くわだてる', '企てる', '<ruby>企<rp>(</rp><rt>くわだ</rt><rp>)</rp></ruby>てる', 'to plan, scheme'),
  new Term('こえる', null, null, 'to get fat, grow fertile / cross over, exceed'),
  new Term('こげる', '焦げる', '<ruby>焦<rp>(</rp><rt>こ</rt><rp>)</rp></ruby>げる', 'to be burned, charred'),
  new Term('こしかける', '腰掛ける', '<ruby>腰<rp>(</rp><rt>こし</rt><rp>)</rp></ruby><ruby>掛<rp>(</rp><rt>か</rt><rp>)</rp></ruby>ける', 'to sit in (western style)'),
  new Term('こしらえる', '拵える', '<ruby>拵<rp>(</rp><rt>こしら</rt><rp>)</rp></ruby>える', 'to make manufacture'),
  new Term('こたえる', '答える', '<ruby>答<rp>(</rp><rt>こた</rt><rp>)</rp></ruby>える', 'to answer'),
  new Term('こぼれる', null, null, 'to spill, overflow'),
  new Term('こわれる', '壊れる', '<ruby>壊<rp>(</rp><rt>こわ</rt><rp>)</rp></ruby>れる', 'to break'),
  new Term('さける', '避ける', '<ruby>避<rp>(</rp><rt>さ</rt><rp>)</rp></ruby>ける', 'to avoid, dodge'),
  new Term('さげる', '下げる', '<ruby>下<rp>(</rp><rt>さ</rt><rp>)</rp></ruby>げる', 'to lower, hang'),
  new Term('ささえる', '支える', '<ruby>支<rp>(</rp><rt>ささ</rt><rp>)</rp></ruby>える', 'to support'),
  new Term('さだめる', '定める', '<ruby>定<rp>(</rp><rt>さだ</rt><rp>)</rp></ruby>める', 'to decide, establish'),
  new Term('さまたげる', '妨げる', '<ruby>妨<rp>(</rp><rt>さまた</rt><rp>)</rp></ruby>げる', 'to hinder, obstruct'),
  new Term('しめる', '閉める', '<ruby>閉<rp>(</rp><rt>し</rt><rp>)</rp></ruby>める', 'to shut'),
  new Term('しらせる', '知らせる', '<ruby>知<rp>(</rp><rt>し</rt><rp>)</rp></ruby>らせる', 'to notify'),
  new Term('しらべる', '調べる', '<ruby>調<rp>(</rp><rt>しら</rt><rp>)</rp></ruby>べる', 'to check, investigate'),
  new Term('しんじる', '信じる', '<ruby>信<rp>(</rp><rt>しん</rt><rp>)</rp></ruby>じる', 'to believe, trust'),
  new Term('すぎる', '過ぎる', '<ruby>過<rp>(</rp><rt>す</rt><rp>)</rp></ruby>ぎる', 'to pass, exceed'),
  new Term('すぐれる', '優れる', '<ruby>優<rp>(</rp><rt>すぐ</rt><rp>)</rp></ruby>れる', 'to excel, be excellent, be superior'),
  new Term('すてる', '捨てる', '<ruby>捨<rp>(</rp><rt>す</rt><rp>)</rp></ruby>てる', 'to throw away'),
  new Term('そだてる', '育てる', '<ruby>育<rp>(</rp><rt>そだ</rt><rp>)</rp></ruby>てる', 'to bring up a child, train'),
  new Term('そだてる', '育てる', '<ruby>育<rp>(</rp><rt>そだ</rt><rp>)</rp></ruby>てる', 'to rear, to bring up'),
  new Term('たおれる', '倒れる', '<ruby>倒<rp>(</rp><rt>たお</rt><rp>)</rp></ruby>れる', 'to fall down, collapse'),
  new Term('たくわえる', '蓄える', '<ruby>蓄<rp>(</rp><rt>たくわ</rt><rp>)</rp></ruby>える', 'to save money, put aside, store'),
  new Term('たすける', '助ける', '<ruby>助<rp>(</rp><rt>たす</rt><rp>)</rp></ruby>ける', 'to help'),
  new Term('たてる', '立てる', '<ruby>立<rp>(</rp><rt>た</rt><rp>)</rp></ruby>てる', 'to build'),
  new Term('たべる', '食べる', '<ruby>食<rp>(</rp><rt>た</rt><rp>)</rp></ruby>べる', 'to eat'),
  new Term('ためる', null, null, 'to save, store, accumulate'),
  new Term('たりる', '足りる', '<ruby>足<rp>(</rp><rt>た</rt><rp>)</rp></ruby>りる', 'to be enough, suffient'),
  new Term('つかれる', '疲れる', '<ruby>疲<rp>(</rp><rt>つか</rt><rp>)</rp></ruby>れる', 'to get tired'),
  new Term('つける', '点ける', '<ruby>点<rp>(</rp><rt>てん</rt><rp>)</rp></ruby>ける', 'to turn on, light'),
  new Term('つづける', '続ける', '<ruby>続<rp>(</rp><rt>つづ</rt><rp>)</rp></ruby>ける', 'to continue, proceed'),
  new Term('つとめる', '勤める', '<ruby>勤<rp>(</rp><rt>つと</rt><rp>)</rp></ruby>める', 'to work for'),
  new Term('つよめる', '強める', '<ruby>強<rp>(</rp><rt>つよ</rt><rp>)</rp></ruby>める', 'to strengthen'),
  new Term('つれる', '連れる', '<ruby>連<rp>(</rp><rt>つ</rt><rp>)</rp></ruby>れる', 'to lead'),
  new Term('でかける', '出かける', '<ruby>出<rp>(</rp><rt>で</rt><rp>)</rp></ruby>かける', 'to go out, leave home'),
  new Term('できる', '出来る', '<ruby>出<rp>(</rp><rt>で</rt><rp>)</rp></ruby><ruby>来<rp>(</rp><rt>き</rt><rp>)</rp></ruby>る', 'to be able'),
  new Term('でる', '出る', '<ruby>出<rp>(</rp><rt>で</rt><rp>)</rp></ruby>る', 'to leave; to come out'),
  new Term('とめる', '止める', '<ruby>止<rp>(</rp><rt>と</rt><rp>)</rp></ruby>める', 'to stop, fasten'),
  new Term('とりかえる', '取り換える', '<ruby>取<rp>(</rp><rt>と</rt><rp>)</rp></ruby>り<ruby>換<rp>(</rp><rt>か</rt><rp>)</rp></ruby>える', 'to exchange'),
  new Term('とれる', '取れる', '<ruby>取<rp>(</rp><rt>と</rt><rp>)</rp></ruby>れる', 'to come off'),
  new Term('ながめる', '眺める', '<ruby>眺<rp>(</rp><rt>なが</rt><rp>)</rp></ruby>める', 'to watch, view'),
  new Term('ながれる', '流れる', '<ruby>流<rp>(</rp><rt>なが</rt><rp>)</rp></ruby>れる', 'to flow, be called off'),
  new Term('なぐさめる', '慰める', '<ruby>慰<rp>(</rp><rt>なぐさ</rt><rp>)</rp></ruby>める', 'to comfort, console'),
  new Term('なげる', '投げる', '<ruby>投<rp>(</rp><rt>な</rt><rp>)</rp></ruby>げる', 'to throw away'),
  new Term('なまける', '怠ける', '<ruby>怠<rp>(</rp><rt>なま</rt><rp>)</rp></ruby>ける', 'to be lazy'),
  new Term('なめる', '舐める', '<ruby>舐<rp>(</rp><rt>な</rt><rp>)</rp></ruby>める', 'to lick'),
  new Term('ならべる', '並べる', '<ruby>並<rp>(</rp><rt>なら</rt><rp>)</rp></ruby>べる', 'to line up, list, arrange in order'),
  new Term('なれる', '慣れる', '<ruby>慣<rp>(</rp><rt>な</rt><rp>)</rp></ruby>れる', 'to get used to, become familiar with'),
  new Term('にげる', '逃げる', '<ruby>逃<rp>(</rp><rt>に</rt><rp>)</rp></ruby>げる', 'to run away, escape'),
  new Term('にる', '似る', '<ruby>似<rp>(</rp><rt>に</rt><rp>)</rp></ruby>る', 'to resemble, be similar to'),
  new Term('ぬれる', '濡れる', '<ruby>濡<rp>(</rp><rt>ぬ</rt><rp>)</rp></ruby>れる', 'to become wet'),
  new Term('ねる', '寝る', '<ruby>寝<rp>(</rp><rt>ね</rt><rp>)</rp></ruby>る', 'to sleep, go to bed'),
  new Term('のせる', null, null, 'to put on top off, put on board'),
  new Term('のりかえる', '乗り換える', '<ruby>乗<rp>(</rp><rt>の</rt><rp>)</rp></ruby>り<ruby>換<rp>(</rp><rt>か</rt><rp>)</rp></ruby>える', 'to transit'),
  new Term('はじめる', '始める', '<ruby>始<rp>(</rp><rt>はじ</rt><rp>)</rp></ruby>める', 'to begin'),
  new Term('はずれる', '外れる', '<ruby>外<rp>(</rp><rt>はず</rt><rp>)</rp></ruby>れる', 'to come off, go wide'),
  new Term('はれる', '晴れる', '<ruby>晴<rp>(</rp><rt>は</rt><rp>)</rp></ruby>れる', 'to clear up, tidy up'),
  new Term('ひきうける', '引き受ける', '<ruby>引<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>き<ruby>受<rp>(</rp><rt>う</rt><rp>)</rp></ruby>ける', 'to take charge of'),
  new Term('ひろめる', '広める', '<ruby>広<rp>(</rp><rt>ひろ</rt><rp>)</rp></ruby>める', 'to spread, make popular'),
  new Term('ふえる', '増える', '<ruby>増<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>える', 'to increase'),
  new Term('ふせる', '伏せる', '<ruby>伏<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>せる', 'to lay face down'),
  new Term('ふれる', '触れる', '<ruby>触<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>れる', 'to touch'),
  new Term('ぶつける', null, null, 'to hit against, throw at'),
  new Term('へる', '減る', '<ruby>減<rp>(</rp><rt>へ</rt><rp>)</rp></ruby>る', 'to pass through, go by'),
  new Term('ほどける', '解ける', '<ruby>解<rp>(</rp><rt>と</rt><rp>)</rp></ruby>ける', 'to come untied, loose'),
  new Term('ほめる', '褒める', '<ruby>褒<rp>(</rp><rt>ほ</rt><rp>)</rp></ruby>める', 'to praise'),
  new Term('ほれる', '惚れる', '<ruby>惚<rp>(</rp><rt>ほ</rt><rp>)</rp></ruby>れる', 'to fall in love'),
  new Term('まける', '負ける', '<ruby>負<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>ける', 'to be defeated, lose a game'),
  new Term('まげる', '曲げる', '<ruby>曲<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>げる', 'to bend, twist'),
  new Term('まぜる', '混ぜる', '<ruby>混<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>ぜる', 'to mix'),
  new Term('まちがえる', '間違える', '<ruby>間<rp>(</rp><rt>ま</rt><rp>)</rp></ruby><ruby>違<rp>(</rp><rt>ちが</rt><rp>)</rp></ruby>える', 'to make a mistake'),
  new Term('みえる', '見える', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>える', 'to be visible, able to see'),
  new Term('みせる', '見せる', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>せる', 'to show'),
  new Term('みつける', '見つける', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>つける', 'to find'),
  new Term('みとめる', '認める', '<ruby>認<rp>(</rp><rt>みと</rt><rp>)</rp></ruby>める', 'to admit, recognize'),
  new Term('みる', '見る', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>る', 'to look'),
  new Term('むかえる', '迎える', '<ruby>迎<rp>(</rp><rt>むか</rt><rp>)</rp></ruby>える', 'to greet, meet, welcome'),
  new Term('もうける', '儲ける', '<ruby>儲<rp>(</rp><rt>もう</rt><rp>)</rp></ruby>ける', 'to profit, make money'),
  new Term('もてる', null, null, 'to be popular'),
  new Term('もとめる', '求める', '<ruby>求<rp>(</rp><rt>もと</rt><rp>)</rp></ruby>める', 'to request, seek, buy, ask'),
  new Term('もれる', '漏れる', '<ruby>漏<rp>(</rp><rt>も</rt><rp>)</rp></ruby>れる', 'to leak, escape'),
  new Term('やける', '焼ける', '<ruby>焼<rp>(</rp><rt>や</rt><rp>)</rp></ruby>ける', 'to burn'),
  new Term('やめる', '辞める', '<ruby>辞<rp>(</rp><rt>や</rt><rp>)</rp></ruby>める', 'to stop, give up, resign'),
  new Term('わかれる', '別れる', '<ruby>別<rp>(</rp><rt>わか</rt><rp>)</rp></ruby>れる', 'to part, separate from, be divided, divorced'),
  new Term('わすれる', '忘れる', '<ruby>忘<rp>(</rp><rt>わす</rt><rp>)</rp></ruby>れる', 'to forget'),
]

var godan = [
  new Term('あう', '会う', '<ruby>会<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>う', 'to meet'),
  new Term('あう', '合う', '<ruby>合<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>う', 'to match, fit'),
  new Term('あおぐ', '仰ぐ', '<ruby>仰<rp>(</rp><rt>あお</rt><rp>)</rp></ruby>ぐ', 'to gaze, look up, respect, fan oneself'),
  new Term('あがる', '上がる', '<ruby>上<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>がる', 'to go up, rise'),
  new Term('あく', '開く', '<ruby>開<rp>(</rp><rt>ひら</rt><rp>)</rp></ruby>く', 'to open, become vacant'),
  new Term('あせる', '焦る', '<ruby>焦<rp>(</rp><rt>あせ</rt><rp>)</rp></ruby>る', 'to be in a hurry, panic'),
  new Term('あそぶ', '遊ぶ', '<ruby>遊<rp>(</rp><rt>あそ</rt><rp>)</rp></ruby>ぶ', 'to play'),
  new Term('あたたまる', '暖まる', '<ruby>暖<rp>(</rp><rt>あたた</rt><rp>)</rp></ruby>まる', 'to get warm, warm up'),
  new Term('あつまる', '集まる', '<ruby>集<rp>(</rp><rt>あつ</rt><rp>)</rp></ruby>まる', 'to gather, assemble'),
  new Term('あぶらぎる', '脂ぎる', '<ruby>脂<rp>(</rp><rt>あぶら</rt><rp>)</rp></ruby>ぎる', 'to be greasy'),
  new Term('あらう', '洗う', '<ruby>洗<rp>(</rp><rt>あら</rt><rp>)</rp></ruby>う', 'to wash'),
  new Term('ある', '有る', '<ruby>有<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>る', 'to have, exist'),
  new Term('あるく', '歩く', '<ruby>歩<rp>(</rp><rt>ある</rt><rp>)</rp></ruby>く', 'to walk'),
  new Term('いいあらわす', '言い表す', '<ruby>言<rp>(</rp><rt>い</rt><rp>)</rp></ruby>い<ruby>表<rp>(</rp><rt>あらわ</rt><rp>)</rp></ruby>す', 'to describe'),
  new Term('いいかえる', '言い換える', '<ruby>言<rp>(</rp><rt>い</rt><rp>)</rp></ruby>い<ruby>換<rp>(</rp><rt>か</rt><rp>)</rp></ruby>える', 'to talk back, retort'),
  new Term('いいだす', '言い出す', '<ruby>言<rp>(</rp><rt>い</rt><rp>)</rp></ruby>い<ruby>出<rp>(</rp><rt>だ</rt><rp>)</rp></ruby>す', 'to suggest, start talking'),
  new Term('いいふらす', '言いふらす', '<ruby>言<rp>(</rp><rt>い</rt><rp>)</rp></ruby>いふらす', 'to spread a rumour/story'),
  new Term('いう', '言う', '<ruby>言<rp>(</rp><rt>い</rt><rp>)</rp></ruby>う', 'to say'),
  new Term('いく', '行く', '<ruby>行<rp>(</rp><rt>い</rt><rp>)</rp></ruby>く', 'to go'),
  new Term('いそぐ', '急ぐ', '<ruby>急<rp>(</rp><rt>いそ</rt><rp>)</rp></ruby>ぐ', 'to hurry'),
  new Term('いたむ', '痛む', '<ruby>痛<rp>(</rp><rt>いた</rt><rp>)</rp></ruby>む', 'to become hurt, damaged'),
  new Term('いつわる', '偽る', '<ruby>偽<rp>(</rp><rt>いつわ</rt><rp>)</rp></ruby>る', 'to deceive, lie'),
  new Term('いのる', '祈る', '<ruby>祈<rp>(</rp><rt>いの</rt><rp>)</rp></ruby>る', 'to pray, wish for'),
  new Term('いばる', '威張る', '<ruby>威<rp>(</rp><rt>い</rt><rp>)</rp></ruby><ruby>張<rp>(</rp><rt>ば</rt><rp>)</rp></ruby>る', 'to boast'),
  new Term('いやがる', '嫌がる', '<ruby>嫌<rp>(</rp><rt>いや</rt><rp>)</rp></ruby>がる', 'to dislike, hate'),
  new Term('いる', '要る', '<ruby>要<rp>(</rp><rt>い</rt><rp>)</rp></ruby>る', 'to need'),
  new Term('いわう', '祝う', '<ruby>祝<rp>(</rp><rt>いわ</rt><rp>)</rp></ruby>う', 'to celebrate, congratulate'),
  new Term('うごく', '動く', '<ruby>動<rp>(</rp><rt>うご</rt><rp>)</rp></ruby>く', 'to move'),
  new Term('うしなう', '失う', '<ruby>失<rp>(</rp><rt>うしな</rt><rp>)</rp></ruby>う', 'to lose, part with'),
  new Term('うたう', '歌う', '<ruby>歌<rp>(</rp><rt>うた</rt><rp>)</rp></ruby>う', 'to sing'),
  new Term('うる', '売る', '<ruby>売<rp>(</rp><rt>う</rt><rp>)</rp></ruby>る', 'to sell'),
  new Term('えらぶ', '選ぶ', '<ruby>選<rp>(</rp><rt>えら</rt><rp>)</rp></ruby>ぶ', 'to choose, select'),
  new Term('おう', '追う', '<ruby>追<rp>(</rp><rt>お</rt><rp>)</rp></ruby>う', 'to chase, drive away'),
  new Term('おく', '置く', '<ruby>置<rp>(</rp><rt>お</rt><rp>)</rp></ruby>く', 'to put, place'),
  new Term('おくる', '送る', '<ruby>送<rp>(</rp><rt>おく</rt><rp>)</rp></ruby>る', 'to send, see off'),
  new Term('おこす', '起こす', '<ruby>起<rp>(</rp><rt>お</rt><rp>)</rp></ruby>こす', 'to wake (somebody) up'),
  new Term('おこる', '怒る', '<ruby>怒<rp>(</rp><rt>おこ</rt><rp>)</rp></ruby>る', 'to get angry'),
  new Term('おこる', '起こる', '<ruby>起<rp>(</rp><rt>お</rt><rp>)</rp></ruby>こる', 'to occur, happen'),
  new Term('おしむ', '惜しむ', '<ruby>惜<rp>(</rp><rt>お</rt><rp>)</rp></ruby>しむ', 'to regret, be reluctant'),
  new Term('おす', '押す', '<ruby>押<rp>(</rp><rt>お</rt><rp>)</rp></ruby>す', 'to push, press'),
  new Term('おそう', '襲う', '<ruby>襲<rp>(</rp><rt>おそ</rt><rp>)</rp></ruby>う', 'to attack'),
  new Term('おとす', '落とす', '<ruby>落<rp>(</rp><rt>お</rt><rp>)</rp></ruby>とす', 'to lose, drop'),
  new Term('おとる', '劣る', '<ruby>劣<rp>(</rp><rt>おと</rt><rp>)</rp></ruby>る', 'to be worse than, inferior to'),
  new Term('おどる', '踊る', '<ruby>踊<rp>(</rp><rt>おど</rt><rp>)</rp></ruby>る', 'to dance'),
  new Term('おどろく', '驚く', '<ruby>驚<rp>(</rp><rt>おどろ</rt><rp>)</rp></ruby>く', 'to be suprised, amazed'),
  new Term('おもいつく', '思いつく', '<ruby>思<rp>(</rp><rt>おも</rt><rp>)</rp></ruby>いつく', 'to Think of / come into your mind'),
  new Term('おもう', '思う', '<ruby>思<rp>(</rp><rt>おも</rt><rp>)</rp></ruby>う', 'to think'),
  new Term('およぐ', '泳ぐ', '<ruby>泳<rp>(</rp><rt>およ</rt><rp>)</rp></ruby>ぐ', 'to swim'),
  new Term('およぶ', '及ぶ', '<ruby>及<rp>(</rp><rt>およ</rt><rp>)</rp></ruby>ぶ', 'to reach, extend to'),
  new Term('おわる', '終わる', '<ruby>終<rp>(</rp><rt>お</rt><rp>)</rp></ruby>わる', 'to end'),
  new Term('かう', '買う', '<ruby>買<rp>(</rp><rt>か</rt><rp>)</rp></ruby>う', 'to buy'),
  new Term('かう', '飼う', '<ruby>飼<rp>(</rp><rt>か</rt><rp>)</rp></ruby>う', 'to keep (a pet), raise, rear'),
  new Term('かえす', '返す', '<ruby>返<rp>(</rp><rt>かえ</rt><rp>)</rp></ruby>す', 'to give back, return (something to someone)'),
  new Term('かえる', '帰る', '<ruby>帰<rp>(</rp><rt>かえ</rt><rp>)</rp></ruby>る', 'to return'),
  new Term('かかる', '掛かる', '<ruby>掛<rp>(</rp><rt>か</rt><rp>)</rp></ruby>かる', 'to take, begin, be hanging'),
  new Term('かかわる', '関わる', '<ruby>関<rp>(</rp><rt>かか</rt><rp>)</rp></ruby>わる', 'to take part in, affect'),
  new Term('かがやく', '輝く', '<ruby>輝<rp>(</rp><rt>かがや</rt><rp>)</rp></ruby>く', 'to shine, sparkle'),
  new Term('かぎる', '限る', '<ruby>限<rp>(</rp><rt>かぎ</rt><rp>)</rp></ruby>る', 'to limit'),
  new Term('かく', '書く', '<ruby>書<rp>(</rp><rt>か</rt><rp>)</rp></ruby>く', 'to write'),
  new Term('かくす', '隠す', '<ruby>隠<rp>(</rp><rt>かく</rt><rp>)</rp></ruby>す', 'to hide (something)'),
  new Term('かくれる', '隠れる', '<ruby>隠<rp>(</rp><rt>かく</rt><rp>)</rp></ruby>れる', 'to hide (oneself)'),
  new Term('かける', null, null, 'to run, canter, gallop'),
  new Term('かこむ', '囲む', '<ruby>囲<rp>(</rp><rt>かこ</rt><rp>)</rp></ruby>む', 'to surround, enclose'),
  new Term('かさなる', '重なる', '<ruby>重<rp>(</rp><rt>かさ</rt><rp>)</rp></ruby>なる', 'to be piled up, overlap'),
  new Term('かざる', '飾る', '<ruby>飾<rp>(</rp><rt>かざ</rt><rp>)</rp></ruby>る', 'to decorate, display'),
  new Term('かす', '貸す', '<ruby>貸<rp>(</rp><rt>か</rt><rp>)</rp></ruby>す', 'to lend'),
  new Term('かすむ', '霞む', '<ruby>霞<rp>(</rp><rt>かす</rt><rp>)</rp></ruby>む', 'to become blurred, hazy'),
  new Term('かせぐ', '稼ぐ', '<ruby>稼<rp>(</rp><rt>かせ</rt><rp>)</rp></ruby>ぐ', 'to make money, earn a living'),
  new Term('かたまる', '固まる', '<ruby>固<rp>(</rp><rt>かた</rt><rp>)</rp></ruby>まる', 'to become hard, bunch up'),
  new Term('かたむく', '傾く', '<ruby>傾<rp>(</rp><rt>かたむ</rt><rp>)</rp></ruby>く', 'to lean towards, tilt'),
  new Term('かつ', '勝つ', '<ruby>勝<rp>(</rp><rt>か</rt><rp>)</rp></ruby>つ', 'to win'),
  new Term('かつぐ', '担ぐ', '<ruby>担<rp>(</rp><rt>かつ</rt><rp>)</rp></ruby>ぐ', 'to carry on one&#39;s shoulders'),
  new Term('かなう', '適う', '<ruby>適<rp>(</rp><rt>かな</rt><rp>)</rp></ruby>う', 'to suit, conform to'),
  new Term('かなしむ', '悲しむ', '<ruby>悲<rp>(</rp><rt>かな</rt><rp>)</rp></ruby>しむ', 'to be sad, grieve'),
  new Term('かばう', '庇う', '<ruby>庇<rp>(</rp><rt>かば</rt><rp>)</rp></ruby>う', 'to protect, look after'),
  new Term('かぶる', '被る', '<ruby>被<rp>(</rp><rt>こうむ</rt><rp>)</rp></ruby>る', 'to wear (on your head), put on'),
  new Term('かまう', '構う', '<ruby>構<rp>(</rp><rt>かま</rt><rp>)</rp></ruby>う', 'to care about, mind'),
  new Term('かむ', '噛む', '<ruby>噛<rp>(</rp><rt>か</rt><rp>)</rp></ruby>む', 'to bite'),
  new Term('かよう', '通う', '<ruby>通<rp>(</rp><rt>かよ</rt><rp>)</rp></ruby>う', 'to commute'),
  new Term('からかう', null, null, 'to make fun of, play jokes on'),
  new Term('かわいがる', '可愛がる', '<ruby>可愛<rp>(</rp><rt>かわい</rt><rp>)</rp></ruby>がる', 'to love, be affectionate, tender'),
  new Term('かわかす', '乾かす', '<ruby>乾<rp>(</rp><rt>かわ</rt><rp>)</rp></ruby>かす', 'to dry'),
  new Term('かわく', '乾く', '<ruby>乾<rp>(</rp><rt>かわ</rt><rp>)</rp></ruby>く', 'to become dry'),
  new Term('かわる', '変わる', '<ruby>変<rp>(</rp><rt>か</rt><rp>)</rp></ruby>わる', 'to change'),
  new Term('がんばる', '頑張る', '<ruby>頑<rp>(</rp><rt>がん</rt><rp>)</rp></ruby><ruby>張<rp>(</rp><rt>ば</rt><rp>)</rp></ruby>る', 'to stand firm, try your best'),
  new Term('きく', '聞く', '<ruby>聞<rp>(</rp><rt>き</rt><rp>)</rp></ruby>く', 'to listen'),
  new Term('きづかう', '気遣う', '<ruby>気<rp>(</rp><rt>き</rt><rp>)</rp></ruby><ruby>遣<rp>(</rp><rt>づか</rt><rp>)</rp></ruby>う', 'to worry about, consider'),
  new Term('きづく', '気付く', '<ruby>気<rp>(</rp><rt>き</rt><rp>)</rp></ruby><ruby>付<rp>(</rp><rt>づ</rt><rp>)</rp></ruby>く', 'to sense, realize, notice'),
  new Term('きまる', '決まる', '<ruby>決<rp>(</rp><rt>き</rt><rp>)</rp></ruby>まる', 'to be decided, agreed upon'),
  new Term('きる', '切る', '<ruby>切<rp>(</rp><rt>き</rt><rp>)</rp></ruby>る', 'to cut'),
  new Term('くいちがう', '食い違う', '<ruby>食<rp>(</rp><rt>く</rt><rp>)</rp></ruby>い<ruby>違<rp>(</rp><rt>ちが</rt><rp>)</rp></ruby>う', 'to clash, disagree'),
  new Term('くさる', '腐る', '<ruby>腐<rp>(</rp><rt>くさ</rt><rp>)</rp></ruby>る', 'to decay, go bad, be depressed'),
  new Term('くずす', '崩す', '<ruby>崩<rp>(</rp><rt>くず</rt><rp>)</rp></ruby>す', 'to destroy, break down'),
  new Term('くだく', '砕く', '<ruby>砕<rp>(</rp><rt>くだ</rt><rp>)</rp></ruby>く', 'to crush,  smash'),
  new Term('くどく', '口説く', '<ruby>口<rp>(</rp><rt>く</rt><rp>)</rp></ruby><ruby>説<rp>(</rp><rt>ど</rt><rp>)</rp></ruby>く', 'to persuade, make advances (to a woman)'),
  new Term('くむ', '組む', '<ruby>組<rp>(</rp><rt>く</rt><rp>)</rp></ruby>む', 'to unite, put together'),
  new Term('くもる', '曇る', '<ruby>曇<rp>(</rp><rt>くも</rt><rp>)</rp></ruby>る', 'to get cloudy'),
  new Term('くらす', '暮らす', '<ruby>暮<rp>(</rp><rt>く</rt><rp>)</rp></ruby>らす', 'to live'),
  new Term('くらむ', '眩む', '<ruby>眩<rp>(</rp><rt>くら</rt><rp>)</rp></ruby>む', 'to be blinded, get dizzy'),
  new Term('くりかえす', '繰り返す', '<ruby>繰<rp>(</rp><rt>く</rt><rp>)</rp></ruby>り<ruby>返<rp>(</rp><rt>かえ</rt><rp>)</rp></ruby>す', 'to repeat'),
  new Term('くる', '来る', '<ruby>来<rp>(</rp><rt>く</rt><rp>)</rp></ruby>る', 'to come'),
  new Term('くるう', '狂う', '<ruby>狂<rp>(</rp><rt>くる</rt><rp>)</rp></ruby>う', 'to go mad, be out of order'),
  new Term('くるしむ', '苦しむ', '<ruby>苦<rp>(</rp><rt>くる</rt><rp>)</rp></ruby>しむ', 'to suffer'),
  new Term('けす', '消す', '<ruby>消<rp>(</rp><rt>け</rt><rp>)</rp></ruby>す', 'to turn off, erase'),
  new Term('ける', '蹴る', '<ruby>蹴<rp>(</rp><rt>け</rt><rp>)</rp></ruby>る', 'to kick'),
  new Term('こころざす', '志す', '<ruby>志<rp>(</rp><rt>こころざ</rt><rp>)</rp></ruby>す', 'to aspire to'),
  new Term('こす', '越す', '<ruby>越<rp>(</rp><rt>こ</rt><rp>)</rp></ruby>す', 'to cross, pass, move ahead'),
  new Term('ことなる', '異なる', '<ruby>異<rp>(</rp><rt>こと</rt><rp>)</rp></ruby>なる', 'to be different from'),
  new Term('ことわる', '断わる', '<ruby>断<rp>(</rp><rt>こと</rt><rp>)</rp></ruby>わる', 'to refuse, decline'),
  new Term('このむ', '好む', '<ruby>好<rp>(</rp><rt>この</rt><rp>)</rp></ruby>む', 'to like'),
  new Term('こぼす', null, null, 'to spill'),
  new Term('こまる', '困る', '<ruby>困<rp>(</rp><rt>こま</rt><rp>)</rp></ruby>る', 'to be in trouble'),
  new Term('こむ', '込む', '<ruby>込<rp>(</rp><rt>こ</rt><rp>)</rp></ruby>む', 'to become crowded'),
  new Term('こらす', '凝らす', '<ruby>凝<rp>(</rp><rt>こ</rt><rp>)</rp></ruby>らす', 'to concentrate'),
  new Term('ころす', '殺す', '<ruby>殺<rp>(</rp><rt>ころ</rt><rp>)</rp></ruby>す', 'to kill'),
  new Term('ころぶ', '転ぶ', '<ruby>転<rp>(</rp><rt>ころ</rt><rp>)</rp></ruby>ぶ', 'to fall down'),
  new Term('こわがる', '怖がる', '<ruby>怖<rp>(</rp><rt>こわ</rt><rp>)</rp></ruby>がる', 'to fear'),
  new Term('こわす', '壊す', '<ruby>壊<rp>(</rp><rt>こわ</rt><rp>)</rp></ruby>す', 'to smash'),
  new Term('さがす', '探す', '<ruby>探<rp>(</rp><rt>さが</rt><rp>)</rp></ruby>す', 'to search for'),
  new Term('さがる', '下がる', '<ruby>下<rp>(</rp><rt>さ</rt><rp>)</rp></ruby>がる', 'to fall, drop, hang'),
  new Term('さく', '咲く', '<ruby>咲<rp>(</rp><rt>さ</rt><rp>)</rp></ruby>く', 'to bloom'),
  new Term('さす', '刺す', '<ruby>刺<rp>(</rp><rt>さ</rt><rp>)</rp></ruby>す', 'to point out, sting, stab'),
  new Term('さそう', '誘う', '<ruby>誘<rp>(</rp><rt>さそ</rt><rp>)</rp></ruby>う', 'to invite, tempt'),
  new Term('さわぐ', '騒ぐ', '<ruby>騒<rp>(</rp><rt>さわ</rt><rp>)</rp></ruby>ぐ', 'to make a noise, be rowdy'),
  new Term('さわる', '触る', '<ruby>触<rp>(</rp><rt>さわ</rt><rp>)</rp></ruby>る', 'to touch or feel (with hands)'),
  new Term('しかる', '叱る', '<ruby>叱<rp>(</rp><rt>しか</rt><rp>)</rp></ruby>る', 'to scold, tell off'),
  new Term('しく', '敷く', '<ruby>敷<rp>(</rp><rt>し</rt><rp>)</rp></ruby>く', 'to spread out, lay'),
  new Term('しずまる', '静まる', '<ruby>静<rp>(</rp><rt>しず</rt><rp>)</rp></ruby>まる', 'to grow quiet'),
  new Term('しずむ', '沈む', '<ruby>沈<rp>(</rp><rt>しず</rt><rp>)</rp></ruby>む', 'to feel depressed, sink'),
  new Term('しぬ', '死ぬ', '<ruby>死<rp>(</rp><rt>し</rt><rp>)</rp></ruby>ぬ', 'to die'),
  new Term('しばる', '縛る', '<ruby>縛<rp>(</rp><rt>しば</rt><rp>)</rp></ruby>る', 'to tie up, bind'),
  new Term('しまう', null, null, 'to put away'),
  new Term('しまる', '閉まる', '<ruby>閉<rp>(</rp><rt>し</rt><rp>)</rp></ruby>まる', 'to close, be closed'),
  new Term('しめす', '示す', '<ruby>示<rp>(</rp><rt>しめ</rt><rp>)</rp></ruby>す', 'to indicate, point out'),
  new Term('しゃべる', '喋る', '<ruby>喋<rp>(</rp><rt>しゃべ</rt><rp>)</rp></ruby>る', 'to chatter'),
  new Term('しる', '知る', '<ruby>知<rp>(</rp><rt>し</rt><rp>)</rp></ruby>る', 'to know'),
  new Term('じゅくす', '熟す', '<ruby>熟<rp>(</rp><rt>じゅく</rt><rp>)</rp></ruby>す', 'to mature, ripen'),
  new Term('すう', '吸う', '<ruby>吸<rp>(</rp><rt>す</rt><rp>)</rp></ruby>う', 'to inhale, sip, smoke'),
  new Term('すく', '空く', '<ruby>空<rp>(</rp><rt>す</rt><rp>)</rp></ruby>く', 'to become empty, uncrowded'),
  new Term('すくう', '救う', '<ruby>救<rp>(</rp><rt>すく</rt><rp>)</rp></ruby>う', 'to rescue, save'),
  new Term('すすむ', '進む', '<ruby>進<rp>(</rp><rt>すす</rt><rp>)</rp></ruby>む', 'to go forward, advance'),
  new Term('すべる', '滑る', '<ruby>滑<rp>(</rp><rt>すべ</rt><rp>)</rp></ruby>る', 'to slip'),
  new Term('すむ', '住む', '<ruby>住<rp>(</rp><rt>す</rt><rp>)</rp></ruby>む', 'to live, reside'),
  new Term('すわる', '座る', '<ruby>座<rp>(</rp><rt>すわ</rt><rp>)</rp></ruby>る', 'to sit'),
  new Term('そだつ', '育つ', '<ruby>育<rp>(</rp><rt>そだ</rt><rp>)</rp></ruby>つ', 'to grow up, be raised'),
  new Term('たおす', '倒す', '<ruby>倒<rp>(</rp><rt>たお</rt><rp>)</rp></ruby>す', 'to overthrow, knock down'),
  new Term('たくらむ', '企む', '<ruby>企<rp>(</rp><rt>たくら</rt><rp>)</rp></ruby>む', 'to plot, scheme'),
  new Term('たける', '猛る', '<ruby>猛<rp>(</rp><rt>たけ</rt><rp>)</rp></ruby>る', 'to act violently'),
  new Term('たす', '足す', '<ruby>足<rp>(</rp><rt>た</rt><rp>)</rp></ruby>す', 'to add'),
  new Term('たたむ', '畳む', '<ruby>畳<rp>(</rp><rt>たた</rt><rp>)</rp></ruby>む', 'to fold'),
  new Term('たつ', '立つ', '<ruby>立<rp>(</rp><rt>た</rt><rp>)</rp></ruby>つ', 'to stand up'),
  new Term('たのしむ', '楽しむ', '<ruby>楽<rp>(</rp><rt>たの</rt><rp>)</rp></ruby>しむ', 'to enjoy, have fun'),
  new Term('たのむ', '頼む', '<ruby>頼<rp>(</rp><rt>たの</rt><rp>)</rp></ruby>む', 'to request, order, ask favour'),
  new Term('たまる', '貯める', '<ruby>貯<rp>(</rp><rt>た</rt><rp>)</rp></ruby>める', 'to be saved, accumulated'),
  new Term('ためす', '試す', '<ruby>試<rp>(</rp><rt>ため</rt><rp>)</rp></ruby>す', 'to test, try, taste'),
  new Term('だく', '抱く', '<ruby>抱<rp>(</rp><rt>いだ</rt><rp>)</rp></ruby>く', 'to embrace, hug'),
  new Term('だす', '出す', '<ruby>出<rp>(</rp><rt>だ</rt><rp>)</rp></ruby>す', 'to extract, take out'),
  new Term('だます', '騙す', '<ruby>騙<rp>(</rp><rt>だま</rt><rp>)</rp></ruby>す', 'to trick'),
  new Term('だまる', '黙る', '<ruby>黙<rp>(</rp><rt>だま</rt><rp>)</rp></ruby>る', 'to stop talking'),
  new Term('ちがう', '違う', '<ruby>違<rp>(</rp><rt>ちが</rt><rp>)</rp></ruby>う', 'to be different, wrong'),
  new Term('ちる', '散る', '<ruby>散<rp>(</rp><rt>ち</rt><rp>)</rp></ruby>る', 'to fall, scatter'),
  new Term('つかう', '使う', '<ruby>使<rp>(</rp><rt>つか</rt><rp>)</rp></ruby>う', 'to use, operate'),
  new Term('つく', '着く', '<ruby>着<rp>(</rp><rt>つ</rt><rp>)</rp></ruby>く', 'to arrive'),
  new Term('つくる', '作る', '<ruby>作<rp>(</rp><rt>つく</rt><rp>)</rp></ruby>る', 'to make, build, create'),
  new Term('つぐ', '次ぐ', '<ruby>次<rp>(</rp><rt>つ</rt><rp>)</rp></ruby>ぐ', 'to be next'),
  new Term('つつむ', '包む', '<ruby>包<rp>(</rp><rt>つつ</rt><rp>)</rp></ruby>む', 'to wrap'),
  new Term('つづく', '続く', '<ruby>続<rp>(</rp><rt>つづ</rt><rp>)</rp></ruby>く', 'to continue, follow'),
  new Term('つよまる', '強まる', '<ruby>強<rp>(</rp><rt>つよ</rt><rp>)</rp></ruby>まる', 'to become stronger'),
  new Term('つる', '釣る', '<ruby>釣<rp>(</rp><rt>つ</rt><rp>)</rp></ruby>る', 'to fish'),
  new Term('てつだう', '手伝う', '<ruby>手<rp>(</rp><rt>て</rt><rp>)</rp></ruby><ruby>伝<rp>(</rp><rt>つだ</rt><rp>)</rp></ruby>う', 'to help'),
  new Term('とどく', '届く', '<ruby>届<rp>(</rp><rt>とど</rt><rp>)</rp></ruby>く', 'to reach'),
  new Term('とぶ', '飛ぶ', '<ruby>飛<rp>(</rp><rt>と</rt><rp>)</rp></ruby>ぶ', 'to jump, fly'),
  new Term('とまる', '止まる', '<ruby>止<rp>(</rp><rt>と</rt><rp>)</rp></ruby>まる', 'to stop'),
  new Term('とる', '取る', '<ruby>取<rp>(</rp><rt>と</rt><rp>)</rp></ruby>る', 'to take, steal'),
  new Term('どじる', null, null, 'to mess up'),
  new Term('なおす', '直す', '<ruby>直<rp>(</rp><rt>なお</rt><rp>)</rp></ruby>す', 'to repair, cure'),
  new Term('なおる', '治る', '<ruby>治<rp>(</rp><rt>なお</rt><rp>)</rp></ruby>る', 'to be cured, healed'),
  new Term('ながす', '流す', '<ruby>流<rp>(</rp><rt>なが</rt><rp>)</rp></ruby>す', 'to pour, let flow'),
  new Term('なく', '鳴く', '<ruby>鳴<rp>(</rp><rt>な</rt><rp>)</rp></ruby>く', 'to cry'),
  new Term('なくす', '無くす', '<ruby>無<rp>(</rp><rt>な</rt><rp>)</rp></ruby>くす', 'to lose, remove'),
  new Term('なくなる', '無くなる', '<ruby>無<rp>(</rp><rt>な</rt><rp>)</rp></ruby>くなる', 'to be missing, vanish'),
  new Term('なぐる', '殴る', '<ruby>殴<rp>(</rp><rt>なぐ</rt><rp>)</rp></ruby>る', 'to punch, hit'),
  new Term('なじむ', '馴染む', '<ruby>馴<rp>(</rp><rt>な</rt><rp>)</rp></ruby><ruby>染<rp>(</rp><rt>じ</rt><rp>)</rp></ruby>む', 'to get used to, adapt to'),
  new Term('ならう', '習う', '<ruby>習<rp>(</rp><rt>なら</rt><rp>)</rp></ruby>う', 'to learn'),
  new Term('ならぶ', '並ぶ', '<ruby>並<rp>(</rp><rt>なら</rt><rp>)</rp></ruby>ぶ', 'to form a line, equal'),
  new Term('なる', '成る', '<ruby>成<rp>(</rp><rt>な</rt><rp>)</rp></ruby>る', 'to become'),
  new Term('にぎる', '握る', '<ruby>握<rp>(</rp><rt>にぎ</rt><rp>)</rp></ruby>る', 'to grasp'),
  new Term('にらむ', '睨む', '<ruby>睨<rp>(</rp><rt>にら</rt><rp>)</rp></ruby>む', 'to glare at, keep an eye on'),
  new Term('ぬぐ', '脱ぐ', '<ruby>脱<rp>(</rp><rt>ぬ</rt><rp>)</rp></ruby>ぐ', 'to remove'),
  new Term('ぬぐ', '脱ぐ', '<ruby>脱<rp>(</rp><rt>ぬ</rt><rp>)</rp></ruby>ぐ', 'to take off, remove (shoes, clothes)'),
  new Term('ぬすむ', '盗む', '<ruby>盗<rp>(</rp><rt>ぬす</rt><rp>)</rp></ruby>む', 'to steal'),
  new Term('ぬる', '塗る', '<ruby>塗<rp>(</rp><rt>ぬ</rt><rp>)</rp></ruby>る', 'to paint'),
  new Term('ぬる', '塗る', '<ruby>塗<rp>(</rp><rt>ぬ</rt><rp>)</rp></ruby>る', 'to smear on'),
  new Term('ねじる', '捩じる', '<ruby>捩<rp>(</rp><rt>ね</rt><rp>)</rp></ruby>じる', 'to twist'),
  new Term('ねむる', '眠る', '<ruby>眠<rp>(</rp><rt>ねむ</rt><rp>)</rp></ruby>る', 'to fall asleep'),
  new Term('のこす', '残す', '<ruby>残<rp>(</rp><rt>のこ</rt><rp>)</rp></ruby>す', 'to leave behind, save'),
  new Term('のこる', '残る', '<ruby>残<rp>(</rp><rt>のこ</rt><rp>)</rp></ruby>る', 'to left over, remain'),
  new Term('ののしる', '罵る', '<ruby>罵<rp>(</rp><rt>ののし</rt><rp>)</rp></ruby>る', 'to abuse verbally, curse'),
  new Term('のばす', '延ばす', '<ruby>延<rp>(</rp><rt>の</rt><rp>)</rp></ruby>ばす', 'to postpone, extend'),
  new Term('のぼる', '登る', '<ruby>登<rp>(</rp><rt>のぼ</rt><rp>)</rp></ruby>る', 'to climb'),
  new Term('のむ', '飲む', '<ruby>飲<rp>(</rp><rt>の</rt><rp>)</rp></ruby>む', 'to drink'),
  new Term('のる', '乗る', '<ruby>乗<rp>(</rp><rt>の</rt><rp>)</rp></ruby>る', 'to board, ride on'),
  new Term('はいる', '入る', '<ruby>入<rp>(</rp><rt>はい</rt><rp>)</rp></ruby>る', 'to enter'),
  new Term('はく', '履く', '<ruby>履<rp>(</rp><rt>は</rt><rp>)</rp></ruby>く', 'to put on, wear (on feet or legs - trousers/shoes etc)'),
  new Term('はげます', '励ます', '<ruby>励<rp>(</rp><rt>はげ</rt><rp>)</rp></ruby>ます', 'to encourage'),
  new Term('はげむ', '励む', '<ruby>励<rp>(</rp><rt>はげ</rt><rp>)</rp></ruby>む', 'to strive, make every effort'),
  new Term('はこぶ', '運ぶ', '<ruby>運<rp>(</rp><rt>はこ</rt><rp>)</rp></ruby>ぶ', 'to carry'),
  new Term('はさむ', '挟む', '<ruby>挟<rp>(</rp><rt>はさ</rt><rp>)</rp></ruby>む', 'to catch, hold (between two things)'),
  new Term('はしる', '走る', '<ruby>走<rp>(</rp><rt>はし</rt><rp>)</rp></ruby>る', 'to run'),
  new Term('はじまる', '始まる', '<ruby>始<rp>(</rp><rt>はじ</rt><rp>)</rp></ruby>まる', 'to begin'),
  new Term('はずす', '外す', '<ruby>外<rp>(</rp><rt>はず</rt><rp>)</rp></ruby>す', 'to remove, unfasten'),
  new Term('はたらく', '働く', '<ruby>働<rp>(</rp><rt>はたら</rt><rp>)</rp></ruby>く', 'to work'),
  new Term('はなしあう', '話し合う', '<ruby>話<rp>(</rp><rt>はな</rt><rp>)</rp></ruby>し<ruby>合<rp>(</rp><rt>あ</rt><rp>)</rp></ruby>う', 'to Discuss'),
  new Term('はなす', '話す', '<ruby>話<rp>(</rp><rt>はな</rt><rp>)</rp></ruby>す', 'to speak'),
  new Term('はなれる', '離れる', '<ruby>離<rp>(</rp><rt>はな</rt><rp>)</rp></ruby>れる', 'to separate from, leave'),
  new Term('はべる', '侍る', '<ruby>侍<rp>(</rp><rt>はべ</rt><rp>)</rp></ruby>る', 'to attend on'),
  new Term('はやる', '流行る', '<ruby>流行<rp>(</rp><rt>はや</rt><rp>)</rp></ruby>る', 'to become popular'),
  new Term('はらう', '払う', '<ruby>払<rp>(</rp><rt>はら</rt><rp>)</rp></ruby>う', 'to pay'),
  new Term('はる', '張る', '<ruby>張<rp>(</rp><rt>は</rt><rp>)</rp></ruby>る', 'to stick, put something on'),
  new Term('ひかる', '光る', '<ruby>光<rp>(</rp><rt>ひか</rt><rp>)</rp></ruby>る', 'to shine, glitter'),
  new Term('ひく', '引く', '<ruby>引<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>く', 'to pull'),
  new Term('ひく', '弾く', '<ruby>弾<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>く', 'to play (string instrument)'),
  new Term('ひねる', '捻る', '<ruby>捻<rp>(</rp><rt>ひね</rt><rp>)</rp></ruby>る', 'to bend, twist'),
  new Term('ひやかす', '冷やかす', '<ruby>冷<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>やかす', 'to tease, make fun of'),
  new Term('ひやす', '冷やす', '<ruby>冷<rp>(</rp><rt>ひ</rt><rp>)</rp></ruby>やす', 'to cool, refridgerate'),
  new Term('ひらく', '開く', '<ruby>開<rp>(</rp><rt>ひら</rt><rp>)</rp></ruby>く', 'to open, hold (an event, party etc)'),
  new Term('ひろう', '拾う', '<ruby>拾<rp>(</rp><rt>ひろ</rt><rp>)</rp></ruby>う', 'to pick up, find'),
  new Term('ひろまる', '広まる', '<ruby>広<rp>(</rp><rt>ひろ</rt><rp>)</rp></ruby>まる', 'to spread, become popular'),
  new Term('びびる', null, null, 'to be suprised'),
  new Term('ふく', '吹く', '<ruby>吹<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>く', 'to blow, wipe'),
  new Term('ふける', null, null, 'to be absorbed in'),
  new Term('ふせる', '臥せる', '<ruby>臥<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>せる', 'to lie down'),
  new Term('ふとる', '太る', '<ruby>太<rp>(</rp><rt>ふと</rt><rp>)</rp></ruby>る', 'to get fat, put on weight'),
  new Term('ふむ', '踏む', '<ruby>踏<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>む', 'to step on'),
  new Term('ふる', '降る', '<ruby>降<rp>(</rp><rt>ふ</rt><rp>)</rp></ruby>る', 'to fall from the sky'),
  new Term('ぶつかる', null, null, 'to hit, collide with, clash'),
  new Term('へらす', '減らす', '<ruby>減<rp>(</rp><rt>へ</rt><rp>)</rp></ruby>らす', 'to reduce, decrease'),
  new Term('へる', '減る', '<ruby>減<rp>(</rp><rt>へ</rt><rp>)</rp></ruby>る', 'to decrease, reduce'),
  new Term('ほしがる', '欲しがる', '<ruby>欲<rp>(</rp><rt>ほ</rt><rp>)</rp></ruby>しがる', 'to want, desire'),
  new Term('ほす', '干す', '<ruby>干<rp>(</rp><rt>ほ</rt><rp>)</rp></ruby>す', 'to dry, air'),
  new Term('ほどく', '解く', '<ruby>解<rp>(</rp><rt>と</rt><rp>)</rp></ruby>く', 'to untie'),
  new Term('ほのめかす', '仄めかす', '<ruby>仄<rp>(</rp><rt>ほの</rt><rp>)</rp></ruby>めかす', 'to hint'),
  new Term('ほる', '掘る', '<ruby>掘<rp>(</rp><rt>ほ</rt><rp>)</rp></ruby>る', 'to dig'),
  new Term('ほろびる', '滅びる', '<ruby>滅<rp>(</rp><rt>ほろ</rt><rp>)</rp></ruby>びる', 'to perish'),
  new Term('ほろぼす', '滅ぼす', '<ruby>滅<rp>(</rp><rt>ほろ</rt><rp>)</rp></ruby>ぼす', 'to destroy, ruin'),
  new Term('まいる', '参る', '<ruby>参<rp>(</rp><rt>まい</rt><rp>)</rp></ruby>る', 'to come/go (humble)'),
  new Term('まかす', '負かす', '<ruby>負<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>かす', 'to defeat'),
  new Term('まがる', '曲がる', '<ruby>曲<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>がる', 'to turn, bend'),
  new Term('まじる', '混じる', '<ruby>混<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>じる', 'to be mixed, get mingled with, join'),
  new Term('まちがう', '間違う', '<ruby>間<rp>(</rp><rt>ま</rt><rp>)</rp></ruby><ruby>違<rp>(</rp><rt>ちが</rt><rp>)</rp></ruby>う', 'to be mistaken, make a mistake'),
  new Term('まつ', '待つ', '<ruby>待<rp>(</rp><rt>ま</rt><rp>)</rp></ruby>つ', 'to wait'),
  new Term('まつる', '祀る', '<ruby>祀<rp>(</rp><rt>まつ</rt><rp>)</rp></ruby>る', 'to worship'),
  new Term('まなぶ', '学ぶ', '<ruby>学<rp>(</rp><rt>まな</rt><rp>)</rp></ruby>ぶ', 'to learn, study'),
  new Term('まねく', '招く', '<ruby>招<rp>(</rp><rt>まね</rt><rp>)</rp></ruby>く', 'to invite, beckon to'),
  new Term('まもる', '守る', '<ruby>守<rp>(</rp><rt>まも</rt><rp>)</rp></ruby>る', 'to protect'),
  new Term('まよう', '迷う', '<ruby>迷<rp>(</rp><rt>まよ</rt><rp>)</rp></ruby>う', 'to be puzzled'),
  new Term('まわる', '回る', '<ruby>回<rp>(</rp><rt>まわ</rt><rp>)</rp></ruby>る', 'to go round'),
  new Term('みがく', '磨く', '<ruby>磨<rp>(</rp><rt>みが</rt><rp>)</rp></ruby>く', 'to polish'),
  new Term('みつかる', '見つかる', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby>つかる', 'to be found'),
  new Term('みなす', '見做す', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby><ruby>做<rp>(</rp><rt>做</rt><rp>)</rp></ruby>す', 'to look upon, consider'),
  new Term('みのがす', '見逃す', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby><ruby>逃<rp>(</rp><rt>のが</rt><rp>)</rp></ruby>す', 'to overlook, let pass'),
  new Term('みのる', '実る', '<ruby>実<rp>(</rp><rt>みの</rt><rp>)</rp></ruby>る', 'to ripen, bear fruit'),
  new Term('みはる', '見張る', '<ruby>見<rp>(</rp><rt>み</rt><rp>)</rp></ruby><ruby>張<rp>(</rp><rt>は</rt><rp>)</rp></ruby>る', 'to stand guard, keep lookout'),
  new Term('むかう', '向かう', '<ruby>向<rp>(</rp><rt>む</rt><rp>)</rp></ruby>かう', 'to face, turn/head toward'),
  new Term('むすぶ', '結ぶ', '<ruby>結<rp>(</rp><rt>むす</rt><rp>)</rp></ruby>ぶ', 'to tie, knot, make a contract'),
  new Term('めだつ', '目立つ', '<ruby>目<rp>(</rp><rt>め</rt><rp>)</rp></ruby><ruby>立<rp>(</rp><rt>だ</rt><rp>)</rp></ruby>つ', 'to attract attention, stand out'),
  new Term('もうかる', '儲かる', '<ruby>儲<rp>(</rp><rt>もう</rt><rp>)</rp></ruby>かる', 'to be profitable, make money'),
  new Term('もつ', '持つ', '<ruby>持<rp>(</rp><rt>も</rt><rp>)</rp></ruby>つ', 'to have, hold, own'),
  new Term('もとづく', '基づく', '<ruby>基<rp>(</rp><rt>もと</rt><rp>)</rp></ruby>づく', 'to be based on'),
  new Term('もどす', '戻す', '<ruby>戻<rp>(</rp><rt>もど</rt><rp>)</rp></ruby>す', 'to return, put back, vomit'),
  new Term('もどる', '戻る', '<ruby>戻<rp>(</rp><rt>もど</rt><rp>)</rp></ruby>る', 'to return, go back'),
  new Term('もらう', '貰う', '<ruby>貰<rp>(</rp><rt>もら</rt><rp>)</rp></ruby>う', 'to receive, get'),
  new Term('もらす', '漏らす', '<ruby>漏<rp>(</rp><rt>も</rt><rp>)</rp></ruby>らす', 'to leak, disclose'),
  new Term('やく', '焼く', '<ruby>焼<rp>(</rp><rt>や</rt><rp>)</rp></ruby>く', 'to bake, grill'),
  new Term('やすむ', '休む', '<ruby>休<rp>(</rp><rt>やす</rt><rp>)</rp></ruby>む', 'to rest, sleep'),
  new Term('やる', null, null, 'to do, give'),
  new Term('よぶ', '呼ぶ', '<ruby>呼<rp>(</rp><rt>よ</rt><rp>)</rp></ruby>ぶ', 'to call'),
  new Term('よむ', '読む', '<ruby>読<rp>(</rp><rt>よ</rt><rp>)</rp></ruby>む', 'to read'),
  new Term('よろこぶ', '喜ぶ', '<ruby>喜<rp>(</rp><rt>よろこ</rt><rp>)</rp></ruby>ぶ', 'to be glad, pleased'),
  new Term('わかる', '分かる', '<ruby>分<rp>(</rp><rt>わ</rt><rp>)</rp></ruby>かる', 'to understand'),
  new Term('わたす', '渡す', '<ruby>渡<rp>(</rp><rt>わた</rt><rp>)</rp></ruby>す', 'to hand over'),
  new Term('わたる', '渡る', '<ruby>渡<rp>(</rp><rt>わた</rt><rp>)</rp></ruby>る', 'to cross'),
  new Term('わらう', '笑う', '<ruby>笑<rp>(</rp><rt>わら</rt><rp>)</rp></ruby>う', 'to laugh'),
]

var ii_adjective = [
  new Term('あおい', '青い', '<ruby>青<rp>(</rp><rt>あお</rt><rp>)</rp></ruby>い', 'blue'),
  new Term('あかい', '赤い', '<ruby>赤<rp>(</rp><rt>あか</rt><rp>)</rp></ruby>い', 'red'),
  new Term('あかるい', '明るい', '<ruby>明<rp>(</rp><rt>あか</rt><rp>)</rp></ruby>るい', 'bright'),
  new Term('あたたかい', '温かい', '<ruby>温<rp>(</rp><rt>あたた</rt><rp>)</rp></ruby>かい', 'warm'),
  new Term('あたらしい', '新しい', '<ruby>新<rp>(</rp><rt>あたら</rt><rp>)</rp></ruby>しい', 'new'),
  new Term('あつい', '暑い', '<ruby>暑<rp>(</rp><rt>あつ</rt><rp>)</rp></ruby>い', 'hot'),
  new Term('あぶない', '危ない', '<ruby>危<rp>(</rp><rt>あぶ</rt><rp>)</rp></ruby>ない', 'dangerous'),
  new Term('あまい', '甘い', '<ruby>甘<rp>(</rp><rt>あま</rt><rp>)</rp></ruby>い', 'sweet'),
  new Term('いそがしい', '忙しい', '<ruby>忙<rp>(</rp><rt>いそが</rt><rp>)</rp></ruby>しい', 'busy'),
  new Term('いたい', '痛い', '<ruby>痛<rp>(</rp><rt>いた</rt><rp>)</rp></ruby>い', 'painful'),
  new Term('うすい', '薄い', '<ruby>薄<rp>(</rp><rt>うす</rt><rp>)</rp></ruby>い', 'thin'),
  new Term('おいしい', '美味しい', '<ruby>美<rp>(</rp><rt>お</rt><rp>)</rp></ruby><ruby>味<rp>(</rp><rt>い</rt><rp>)</rp></ruby>しい', 'delicious'),
  new Term('おおきい', '大きい', '<ruby>大<rp>(</rp><rt>おお</rt><rp>)</rp></ruby>きい', 'big'),
  new Term('おそい', '遅い', '<ruby>遅<rp>(</rp><rt>おそ</rt><rp>)</rp></ruby>い', 'late, slow'),
  new Term('おもい', '重い', '<ruby>重<rp>(</rp><rt>おも</rt><rp>)</rp></ruby>い', 'heavy'),
  new Term('おもしろい', '面白い', '<ruby>面<rp>(</rp><rt>おも</rt><rp>)</rp></ruby><ruby>白<rp>(</rp><rt>しろ</rt><rp>)</rp></ruby>い', 'interesting - funny'),
  new Term('からい', '辛い', '<ruby>辛<rp>(</rp><rt>つら</rt><rp>)</rp></ruby>い', 'hot, spicy'),
  new Term('かるい', '軽い', '<ruby>軽<rp>(</rp><rt>かる</rt><rp>)</rp></ruby>い', 'light (not heavy)'),
  new Term('かわいい', '可愛い', '<ruby>可愛<rp>(</rp><rt>かわzい</rt><rp>)</rp></ruby>い', 'cute, pretty'),
  new Term('きいろい', '黄色い', '<ruby>黄色<rp>(</rp><rt>きいろ</rt><rp>)</rp></ruby>い', 'yellow'),
  new Term('きたない', '汚い', '<ruby>汚<rp>(</rp><rt>きたな</rt><rp>)</rp></ruby>い', 'dirty'),
  new Term('きびしい', '厳しい', '<ruby>厳<rp>(</rp><rt>きび</rt><rp>)</rp></ruby>しい', 'strict'),
  new Term('くらい', '暗い', '<ruby>暗<rp>(</rp><rt>くら</rt><rp>)</rp></ruby>い', 'dark'),
  new Term('くろい', '黒い', '<ruby>黒<rp>(</rp><rt>くろ</rt><rp>)</rp></ruby>い', 'black'),
  new Term('こわい', '怖い', '<ruby>怖<rp>(</rp><rt>こわ</rt><rp>)</rp></ruby>い', 'friightening'),
  new Term('さびしい', '寂しい', '<ruby>寂<rp>(</rp><rt>さび</rt><rp>)</rp></ruby>しい', 'lonely'),
  new Term('さむい', '寒い', '<ruby>寒<rp>(</rp><rt>さむ</rt><rp>)</rp></ruby>い', 'cold'),
  new Term('しろい', '白い', '<ruby>白<rp>(</rp><rt>しろ</rt><rp>)</rp></ruby>い', 'white'),
  new Term('すごい', '凄い', '<ruby>凄<rp>(</rp><rt>すご</rt><rp>)</rp></ruby>い', 'terrific'),
  new Term('すずしい', '涼しい', '<ruby>涼<rp>(</rp><rt>すず</rt><rp>)</rp></ruby>しい', 'cool'),
  new Term('すばらしい', '素晴らしい', '<ruby>素<rp>(</rp><rt>す</rt><rp>)</rp></ruby><ruby>晴<rp>(</rp><rt>ば</rt><rp>)</rp></ruby>らしい', 'wonderful'),
  new Term('せまい', '狭い', '<ruby>狭<rp>(</rp><rt>せま</rt><rp>)</rp></ruby>い', 'narrow'),
  new Term('たかい', '高い', '<ruby>高<rp>(</rp><rt>たか</rt><rp>)</rp></ruby>い', 'expensive, high, tall'),
  new Term('ただしい', '正しい', '<ruby>正<rp>(</rp><rt>ただ</rt><rp>)</rp></ruby>しい', 'correct'),
  new Term('たのしい', '楽しい', '<ruby>楽<rp>(</rp><rt>たの</rt><rp>)</rp></ruby>しい', 'enjoyable, fun'),
  new Term('ちいさい', '小さい', '<ruby>小<rp>(</rp><rt>ちい</rt><rp>)</rp></ruby>さい', 'small'),
  new Term('ちかい', '近い', '<ruby>近<rp>(</rp><rt>ちか</rt><rp>)</rp></ruby>い', 'near, close'),
  new Term('つまらない', '詰らない', '<ruby>詰<rp>(</rp><rt>なじ</rt><rp>)</rp></ruby>らない', 'uninteresting'),
  new Term('つめたい', '冷たたい', '<ruby>冷<rp>(</rp><rt>つめ</rt><rp>)</rp></ruby>たたい', 'cold'),
  new Term('つよい', '強い', '<ruby>強<rp>(</rp><rt>つよ</rt><rp>)</rp></ruby>い', 'strong'),
  new Term('ながい', '長い', '<ruby>長<rp>(</rp><rt>なが</rt><rp>)</rp></ruby>い', 'long'),
  new Term('にがい', '苦い', '<ruby>苦<rp>(</rp><rt>にが</rt><rp>)</rp></ruby>い', 'bitter'),
  new Term('ねむい', '眠い', '<ruby>眠<rp>(</rp><rt>ねむ</rt><rp>)</rp></ruby>い', 'sleepy'),
  new Term('はやい', '早い', '<ruby>早<rp>(</rp><rt>はや</rt><rp>)</rp></ruby>い', 'early'),
  new Term('はやい', '速い', '<ruby>速<rp>(</rp><rt>はや</rt><rp>)</rp></ruby>い', 'fast'),
  new Term('ひくい', '低い', '<ruby>低<rp>(</rp><rt>ひく</rt><rp>)</rp></ruby>い', 'low'),
  new Term('ひどい', '酷い', '<ruby>酷<rp>(</rp><rt>ひど</rt><rp>)</rp></ruby>い', 'awful'),
  new Term('ひろい', '広い', '<ruby>広<rp>(</rp><rt>ひろ</rt><rp>)</rp></ruby>い', 'wide'),
  new Term('ふかい', '深い', '<ruby>深<rp>(</rp><rt>ふか</rt><rp>)</rp></ruby>い', 'deep'),
  new Term('ふとい', '太い', '<ruby>太<rp>(</rp><rt>ふと</rt><rp>)</rp></ruby>い', 'thick - fat'),
  new Term('ふるい', '古い', '<ruby>古<rp>(</rp><rt>ふる</rt><rp>)</rp></ruby>い', 'old'),
  new Term('ほそい', '細い', '<ruby>細<rp>(</rp><rt>ほそ</rt><rp>)</rp></ruby>い', 'thin - fine'),
  new Term('まずい', '不味い', '<ruby>不<rp>(</rp><rt>ま</rt><rp>)</rp></ruby><ruby>味<rp>(</rp><rt>ず</rt><rp>)</rp></ruby>い', 'bad tasting'),
  new Term('まるい', '丸い', '<ruby>丸<rp>(</rp><rt>まる</rt><rp>)</rp></ruby>い', 'round'),
  new Term('みじかい', '短い', '<ruby>短<rp>(</rp><rt>みじか</rt><rp>)</rp></ruby>い', 'short'),
  new Term('むずかしい', '難しい', '<ruby>難<rp>(</rp><rt>むずか</rt><rp>)</rp></ruby>しい', 'difficult'),
  new Term('めずらしい', '珍しい', '<ruby>珍<rp>(</rp><rt>めずら</rt><rp>)</rp></ruby>しい', 'rare'),
  new Term('やさしい', '優しい', '<ruby>優<rp>(</rp><rt>やさ</rt><rp>)</rp></ruby>しい', 'gentle'),
  new Term('やすい', '安い', '<ruby>安<rp>(</rp><rt>やす</rt><rp>)</rp></ruby>い', 'cheap'),
  new Term('やわらかい', '柔らかい', '<ruby>柔<rp>(</rp><rt>やわ</rt><rp>)</rp></ruby>らかい', 'tender - soft'),
  new Term('わかい', '若い', '<ruby>若<rp>(</rp><rt>わか</rt><rp>)</rp></ruby>い', 'young'),
]

var na_adjective = [
  new Term('いっしょうけんめい', '一生懸命', '<ruby>一生懸命<rp>(</rp><rt>いっしょうけんめい</rt><rp>)</rp></ruby>', 'to one’s fullest possibility'),
  new Term('いや', '嫌', '<ruby>嫌<rp>(</rp><rt>いや</rt><rp>)</rp></ruby>', 'unpleasant'),
  new Term('いろいろ', '色々', '<ruby>色々<rp>(</rp><rt>いろいろ</rt><rp>)</rp></ruby>', 'various'),
  new Term('おおぜい', '大勢', '<ruby>大勢<rp>(</rp><rt>たいせい</rt><rp>)</rp></ruby>', 'lots of people, crowded'),
  new Term('かんたん', '簡単', '<ruby>簡単<rp>(</rp><rt>かんたん</rt><rp>)</rp></ruby>', 'easy'),
  new Term('きけん', '危険', '<ruby>危険<rp>(</rp><rt>きけん</rt><rp>)</rp></ruby>', 'dangerous'),
  new Term('きらい', '嫌い', '<ruby>嫌<rp>(</rp><rt>きら</rt><rp>)</rp></ruby>い', 'to not like'),
  new Term('きれい', '綺麗', '<ruby>綺麗<rp>(</rp><rt>きれい</rt><rp>)</rp></ruby>', 'pretty, beautiful'),
  new Term('けっこう', '結構', '<ruby>結構<rp>(</rp><rt>けっこう</rt><rp>)</rp></ruby>', 'wonderful, enviable'),
  new Term('げんき', '元気', '<ruby>元気<rp>(</rp><rt>げんき</rt><rp>)</rp></ruby>', 'healthy'),
  new Term('ざんねん', '残念', '<ruby>残念<rp>(</rp><rt>ざんねん</rt><rp>)</rp></ruby>', 'regrettable, disappointing'),
  new Term('しずか', '静か', '<ruby>静<rp>(</rp><rt>しず</rt><rp>)</rp></ruby>か', 'quiet'),
  new Term('しんぱい', '心配', '<ruby>心配<rp>(</rp><rt>しんぱい</rt><rp>)</rp></ruby>', 'care, worry'),
  new Term('じゅうぶん', '十分', '<ruby>十<rp>(</rp><rt>じゅう</rt><rp>)</rp></ruby><ruby>分<rp>(</rp><rt>ふん</rt><rp>)</rp></ruby>', 'sufficient'),
  new Term('じゆう', '自由', '<ruby>自由<rp>(</rp><rt>じゆう</rt><rp>)</rp></ruby>', 'free, unrestrained'),
  new Term('じょうず', '上手', '<ruby>上手<rp>(</rp><rt>じょうず</rt><rp>)</rp></ruby>', 'good, skilled'),
  new Term('じょうぶ', '丈夫', '<ruby>丈夫<rp>(</rp><rt>じょうぶ</rt><rp>)</rp></ruby>', 'healthy, robust'),
  new Term('すき', '好き', '<ruby>好<rp>(</rp><rt>す</rt><rp>)</rp></ruby>き', 'Like, love'),
  new Term('たいせつ', '大切', '<ruby>大切<rp>(</rp><rt>たいせつ</rt><rp>)</rp></ruby>', 'important, precious'),
  new Term('たいへん', '大変', '<ruby>大変<rp>(</rp><rt>たいへん</rt><rp>)</rp></ruby>', 'Terrible'),
  new Term('だいじょうぶ', '大丈夫', '<ruby>大丈夫<rp>(</rp><rt>だいじょうぶ</rt><rp>)</rp></ruby>', 'OK, fine'),
  new Term('だいすき', '大好き', '<ruby>大<rp>(</rp><rt>だい</rt><rp>)</rp></ruby><ruby>好<rp>(</rp><rt>す</rt><rp>)</rp></ruby>き', 'Passionate'),
  new Term('ていねい', '丁寧', '<ruby>丁寧<rp>(</rp><rt>ていねい</rt><rp>)</rp></ruby>', 'polite'),
  new Term('てきとう', '適当', '<ruby>適当<rp>(</rp><rt>てきとう</rt><rp>)</rp></ruby>', 'proper, suitable'),
  new Term('とくべつ', '特別', '<ruby>特別<rp>(</rp><rt>とくべつ</rt><rp>)</rp></ruby>', 'special'),
  new Term('にぎやか', '賑やか', '<ruby>賑<rp>(</rp><rt>にぎ</rt><rp>)</rp></ruby>やか', 'lively'),
  new Term('ねっしん', '熱心', '<ruby>熱心<rp>(</rp><rt>ねっしん</rt><rp>)</rp></ruby>', 'eager, enthusiastic'),
  new Term('ひつよう', '必要', '<ruby>必要<rp>(</rp><rt>ひつよう</rt><rp>)</rp></ruby>', 'necessary'),
  new Term('ひま', '暇', '<ruby>暇<rp>(</rp><rt>ひま</rt><rp>)</rp></ruby>', 'free (time)'),
  new Term('ふべん', '不便', '<ruby>不便<rp>(</rp><rt>ふべん</rt><rp>)</rp></ruby>', 'inconvenient'),
  new Term('へた', '下手', '<ruby>下手<rp>(</rp><rt>へた</rt><rp>)</rp></ruby>', 'bad at, unskilled'),
  new Term('べんり', '便利', '<ruby>便利<rp>(</rp><rt>べんり</rt><rp>)</rp></ruby>', 'useful, convenient'),
  new Term('まじめ', '真面目', '<ruby>真面目<rp>(</rp><rt>まじめ</rt><rp>)</rp></ruby>', 'serious, earnest'),
  new Term('まっすぐ', '真っ直ぐ', '<ruby>真<rp>(</rp><rt>まっ</rt><rp>)</rp></ruby><ruby>直<rp>(</rp><rt>す</rt><rp>)</rp></ruby>ぐ', 'straight'),
  new Term('むり', '無理', '<ruby>無理<rp>(</rp><rt>むり</rt><rp>)</rp></ruby>', 'unreasonnable'),
  new Term('ゆうめい', '有名', '<ruby>有名<rp>(</rp><rt>ゆうめい</rt><rp>)</rp></ruby>', 'Famous'),
  new Term('らく', '楽', '<ruby>楽<rp>(</rp><rt>らく</rt><rp>)</rp></ruby>', 'comfortable, easy'),
  new Term('りっぱ', '立派', '<ruby>立派<rp>(</rp><rt>りっぱ</rt><rp>)</rp></ruby>', 'excellent, splendid, fine'),
]
